Console.WriteLine("Привет математик)  ");
int numberA = new Random().Next(1, 10);
Console.Write(numberA);
Console.Write("+");
int numberB = new Random().Next(1,10);
Console.Write(numberB);
int sum = numberA + numberB;
Console.Write(" = ");
Console.Write(sum);
Console.Write("!");